/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pjppenjualan;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
//import java.awt.event.KeyEvent;
//import java.awt.print.PrinterException;
import java.sql.Connection;
//import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
//import java.text.MessageFormat;
//import java.util.Calendar;
//import javax.swing.JComboBox;
//import javax.swing.JSpinner;
//import javax.swing.SwingWorker;
//import javax.swing.table.DefaultTableModel;
//import javax.swing.JComboBox;
/**
 *
 * @author HP
 */
public class frmCariBarang extends javax.swing.JFrame {

    Connection Con;
    ResultSet RsBrg;
    Statement stm;
    public frmTransaksi fAB = null;
    private Object[][] dataTable = null;
    private String[] header = {"Kode","Nama Barang","Satuan","Harga Jual","Harga Beli","Stok","Stok Min"};
    
    /**
     * Creates new form frmCariBarang
     */
    public frmCariBarang() {
        initComponents();
        baca_data();
    }
    
    private void open_db()
    { try{
            KoneksiMysql kon = new KoneksiMysql("localhost","root","","penjualan");
            Con = kon.getConnection();
                //System.out.println("Berhasil ");
                }catch (Exception e) {
                    System.out.println("Error : "+e);
                }
    }
    
    private void baca_data()
    {
    try{
    stm = Con.createStatement();//
    RsBrg = stm.executeQuery("select * from barang order by kd_barang");
    
    ResultSetMetaData meta = RsBrg.getMetaData();
    int col = meta.getColumnCount();
    int baris = 0;
    while(RsBrg.next()) {
        baris = RsBrg.getRow();
    }
    
    dataTable = new Object[baris][col];
    int x = 0;
    RsBrg.beforeFirst();
    while(RsBrg.next()) {
        dataTable[x][0] = RsBrg.getString("kd_barang");
        dataTable[x][1] = RsBrg.getString("nm_barang");
        dataTable[x][2] = RsBrg.getString("satuan");
        dataTable[x][3] = RsBrg.getDouble("harga_jual");
        dataTable[x][4] = RsBrg.getDouble("harga_beli");
        dataTable[x][5] = RsBrg.getInt("stok");
        dataTable[x][6] = RsBrg.getInt("stok_min");
        x++;
    }
    daftar_table.setModel(new DefaultTableModel(dataTable,header));
    }
    catch(SQLException e)
    {
    JOptionPane.showMessageDialog(null, e);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dftr_brg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        daftar_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dftr_brg.setText("DAFTAR BARANG");

        daftar_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama Barang", "Satuan", "Harga Jual", "Harga Beli", "Stok ", "Stok Minimal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        daftar_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daftar_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(daftar_table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(dftr_brg)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(dftr_brg)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void daftar_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftar_tableMouseClicked
        // TODO add your handling code here:
        int row=daftar_table.getSelectedRow();
        int tabelBarang = daftar_table.getSelectedRow();
        fAB.idBrg = daftar_table.getValueAt(tabelBarang, 0).toString();
        fAB.namaBrg = daftar_table.getValueAt(tabelBarang, 1).toString();
        fAB.hargaBrg = daftar_table.getValueAt(tabelBarang, 3).toString();
        fAB.itemTerpilih();
        this.dispose();
        
    }//GEN-LAST:event_daftar_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCariBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCariBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCariBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCariBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCariBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable daftar_table;
    private javax.swing.JLabel dftr_brg;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
