/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pjppenjualan;

/**
 *
 * @author HP
 */
public class frmmenu extends javax.swing.JFrame {

    /**
     * Creates new form frmmenu
     */
    public frmmenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        menu_data_brg = new javax.swing.JMenuItem();
        menu_data_kons = new javax.swing.JMenuItem();
        separator_data_master = new javax.swing.JPopupMenu.Separator();
        menu_keluar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        transaksi_data_brg = new javax.swing.JMenuItem();
        transaksi_data_kons = new javax.swing.JMenuItem();
        separator_transaksi = new javax.swing.JPopupMenu.Separator();
        transaksi_keluar = new javax.swing.JMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("jCheckBoxMenuItem4");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setText("Data Master ");

        menu_data_brg.setText("Data Barang");
        menu_data_brg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_data_brgActionPerformed(evt);
            }
        });
        jMenu3.add(menu_data_brg);

        menu_data_kons.setText("Data Konsumen");
        menu_data_kons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_data_konsActionPerformed(evt);
            }
        });
        jMenu3.add(menu_data_kons);
        jMenu3.add(separator_data_master);

        menu_keluar.setText("Keluar");
        menu_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_keluarActionPerformed(evt);
            }
        });
        jMenu3.add(menu_keluar);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Transaksi");

        transaksi_data_brg.setText("Data Barang");
        transaksi_data_brg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksi_data_brgActionPerformed(evt);
            }
        });
        jMenu4.add(transaksi_data_brg);

        transaksi_data_kons.setText("Data Konsumen");
        transaksi_data_kons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksi_data_konsActionPerformed(evt);
            }
        });
        jMenu4.add(transaksi_data_kons);
        jMenu4.add(separator_transaksi);

        transaksi_keluar.setText("Keluar");
        transaksi_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksi_keluarActionPerformed(evt);
            }
        });
        jMenu4.add(transaksi_keluar);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_data_brgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_data_brgActionPerformed
        // TODO add your handling code here:
        new frmBarang().setVisible(true);
    }//GEN-LAST:event_menu_data_brgActionPerformed

    private void menu_data_konsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_data_konsActionPerformed
        // TODO add your handling code here:
        new frmKonsumen().setVisible(true);
    }//GEN-LAST:event_menu_data_konsActionPerformed

    private void menu_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_keluarActionPerformed
        // TODO add your handling code here:
//        dispose();
    }//GEN-LAST:event_menu_keluarActionPerformed

    private void transaksi_data_brgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksi_data_brgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transaksi_data_brgActionPerformed

    private void transaksi_data_konsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksi_data_konsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transaksi_data_konsActionPerformed

    private void transaksi_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksi_keluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transaksi_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem menu_data_brg;
    private javax.swing.JMenuItem menu_data_kons;
    private javax.swing.JMenuItem menu_keluar;
    private javax.swing.JPopupMenu.Separator separator_data_master;
    private javax.swing.JPopupMenu.Separator separator_transaksi;
    private javax.swing.JMenuItem transaksi_data_brg;
    private javax.swing.JMenuItem transaksi_data_kons;
    private javax.swing.JMenuItem transaksi_keluar;
    // End of variables declaration//GEN-END:variables
}
