/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pjppenjualan;

//import javax.swing.JComboBox;
//import javax.swing.JOptionPane;
//import javax.swing.table.DefaultTableModel;
//import java.sql.Connection;
//import java.sql.ResultSet;
//import java.sql.ResultSetMetaData;
//import java.sql.SQLException;
//import java.sql.Statement;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JComboBox;


/**
 *
 * @author HP
 */
public class frmBarang extends javax.swing.JFrame {
    Connection Con;
    ResultSet RsBrg;
    Statement stm;
    Boolean ada = false;
    String sSatuan;
    Boolean edit=false;
//    private DefaultTableModel tableModel = new DefaultTableModel(
//                new Object[][]{}, 
//                new String[]{"Kode", "Nama", "Satuan", "Harga", "Stok", "Stok Min"}
//        );
    private Object[][] dataTable = null;
    private String[] header = {"Kode","Nama Barang","Satuan","Harga","Harga Beli","Stok","Stok Min"};

    /**
     * Creates new form frmBarang
     */
    public frmBarang() {
        initComponents();
        open_db();
        baca_data();
        aktif(false);
        setTombol(true);
    }

    private void setField(){
        int row = hasil_table.getSelectedRow();
        txt_kd_barang.setText((String)hasil_table.getValueAt(row, 0));
        txt_nm_barang.setText((String)hasil_table.getValueAt(row, 1));
        combo_satuan.setSelectedItem((String)hasil_table.getValueAt(row, 2));
        String harga_jual = Double.toString((Double)hasil_table.getValueAt(row, 3));
        txt_harga_jual.setText(harga_jual);
        String harga_beli = Double.toString((Double)hasil_table.getValueAt(row, 4));
        txt_harga_beli.setText(harga_beli);
        String stok = Integer.toString((Integer)hasil_table.getValueAt(row, 5));
        txt_stok.setText(stok);
        String stok_min = Integer.toString((Integer)hasil_table.getValueAt(row, 6));
        txt_stok_min.setText(stok_min);   
    }
    
    private void open_db()
    { try{
            KoneksiMysql kon = new KoneksiMysql("localhost","root","","penjualan");
            Con = kon.getConnection();
                //System.out.println("Berhasil ");
                }catch (Exception e) {
                    System.out.println("Error : "+e);
                }
    }
    
    private void baca_data()
    {
    try{
    stm = Con.createStatement();
    RsBrg = stm.executeQuery("select * from barang");
    
    ResultSetMetaData meta = RsBrg.getMetaData();
    int col = meta.getColumnCount();
    int baris = 0;
    while(RsBrg.next()) {
        baris = RsBrg.getRow();
    }
    
    dataTable = new Object[baris][col];
    int x = 0;
    RsBrg.beforeFirst();
    while(RsBrg.next()) {
        dataTable[x][0] = RsBrg.getString("kd_barang");
        dataTable[x][1] = RsBrg.getString("nm_barang");
        dataTable[x][2] = RsBrg.getString("satuan");
        dataTable[x][3] = RsBrg.getDouble("harga_jual");
        dataTable[x][4] = RsBrg.getDouble("harga_beli");
        dataTable[x][5] = RsBrg.getInt("stok");
        dataTable[x][6] = RsBrg.getInt("stok_min");
        x++;
    }
    hasil_table.setModel(new DefaultTableModel(dataTable,header));
    }
    catch(SQLException e)
    {
    JOptionPane.showMessageDialog(null, e);
    }
    }
    
    private void kosong()
    {
    txt_kd_barang.setText("");
    txt_nm_barang.setText("");
    txt_harga_jual.setText("");
    txt_harga_beli.setText("");
    txt_stok.setText("");
    txt_stok_min.setText("");
    }
    
    private void aktif(boolean x)
    {
    txt_kd_barang.setEditable(x);
    txt_nm_barang.setEditable(x);
    //cmbSatuan.setEditable(x);
    combo_satuan.setEnabled(x);
    txt_harga_jual.setEditable(x);
    txt_harga_beli.setEditable(x);
    txt_stok.setEditable(x);
    txt_stok_min.setEditable(x);
    }
    
    private void setTombol(boolean t)
    {
    btn_tambah.setEnabled(t);
    btn_koreksi.setEnabled(t);
    btn_hapus.setEnabled(t);
    btn_simpan.setEnabled(!t);
    btn_batal.setEnabled(!t);
    btn_keluar.setEnabled(t);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judul = new javax.swing.JLabel();
        kd_barang = new javax.swing.JLabel();
        nm_barang = new javax.swing.JLabel();
        satuan = new javax.swing.JLabel();
        harga_jual = new javax.swing.JLabel();
        stok = new javax.swing.JLabel();
        stok_min = new javax.swing.JLabel();
        txt_kd_barang = new javax.swing.JTextField();
        txt_nm_barang = new javax.swing.JTextField();
        txt_harga_jual = new javax.swing.JTextField();
        combo_satuan = new javax.swing.JComboBox<>();
        txt_stok = new javax.swing.JTextField();
        txt_stok_min = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasil_table = new javax.swing.JTable();
        btn_tambah = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        btn_koreksi = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(300, 0), new java.awt.Dimension(300, 0), new java.awt.Dimension(300, 32767));
        harga_beli = new javax.swing.JLabel();
        txt_harga_beli = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        judul.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        judul.setText("Data Barang");

        kd_barang.setText("Kode Barang");

        nm_barang.setText("Nama Barang");

        satuan.setText("Satuan");

        harga_jual.setText("Harga");

        stok.setText("Stok");

        stok_min.setText("Stok Minimal");

        txt_kd_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kd_barangActionPerformed(evt);
            }
        });

        txt_nm_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nm_barangActionPerformed(evt);
            }
        });

        txt_harga_jual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_harga_jualActionPerformed(evt);
            }
        });

        combo_satuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_satuan.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                combo_satuanHierarchyChanged(evt);
            }
        });
        combo_satuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_satuanActionPerformed(evt);
            }
        });

        txt_stok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stokActionPerformed(evt);
            }
        });

        txt_stok_min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stok_minActionPerformed(evt);
            }
        });

        hasil_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama Barang", "Satuan", "Harga", "Harga Beli", "Stok", "Stok Min"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        hasil_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hasil_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(hasil_table);

        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_koreksi.setText("Koreksi");
        btn_koreksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_koreksiActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        harga_beli.setText("Harga Beli");

        txt_harga_beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_harga_beliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(judul)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_tambah)
                                .addGap(18, 18, 18)
                                .addComponent(btn_simpan)
                                .addGap(18, 18, 18)
                                .addComponent(btn_koreksi)
                                .addGap(18, 18, 18)
                                .addComponent(btn_hapus)
                                .addGap(18, 18, 18)
                                .addComponent(btn_batal)
                                .addGap(18, 18, 18)
                                .addComponent(btn_keluar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kd_barang)
                                    .addComponent(nm_barang)
                                    .addComponent(harga_jual)
                                    .addComponent(satuan)
                                    .addComponent(stok)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(harga_beli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(stok_min, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_kd_barang)
                                    .addComponent(txt_nm_barang)
                                    .addComponent(combo_satuan, 0, 492, Short.MAX_VALUE)
                                    .addComponent(txt_harga_jual)
                                    .addComponent(txt_stok)
                                    .addComponent(txt_stok_min)
                                    .addComponent(txt_harga_beli))))
                        .addGap(0, 133, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judul)
                .addGap(9, 9, 9)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kd_barang)
                    .addComponent(txt_kd_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nm_barang)
                    .addComponent(txt_nm_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(satuan)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(harga_jual)
                            .addComponent(txt_harga_jual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(combo_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(harga_beli)
                    .addComponent(txt_harga_beli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stok)
                    .addComponent(txt_stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stok_min)
                    .addComponent(txt_stok_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah)
                    .addComponent(btn_simpan)
                    .addComponent(btn_koreksi)
                    .addComponent(btn_hapus)
                    .addComponent(btn_batal)
                    .addComponent(btn_keluar))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_kd_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kd_barangActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_kd_barangActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        String tkode = txt_kd_barang.getText();
        String tnama = txt_nm_barang.getText();
//        sSatuan = combo_satuan.getSelectedItem().toString();
//        String tSatuan = (String) combo_satuan.getSelectedItem();
        double hrg = Double.parseDouble(txt_harga_jual.getText());
        double hrg_beli = Double.parseDouble(txt_harga_beli.getText());
        int stk = Integer.parseInt(txt_stok.getText());
        int stk_min = Integer.parseInt(txt_stok_min.getText());
        
        try{
        if (edit==true){
        stm.executeUpdate("update barang set nm_barang='"+tnama+"',satuan='"+sSatuan+"',harga_jual="+hrg+",harga_beli="+hrg_beli+",stok="+stk+",stok_min="+stk_min+" where kd_barang='" + tkode + "'");
        }else
        {
        stm.executeUpdate("INSERT into barang VALUES('"+tkode+"','"+tnama+"','"+sSatuan+"',"+hrg+","+hrg_beli+","+stk+","+stk_min+")");
        }
        hasil_table.setModel(new DefaultTableModel(dataTable,header));
        baca_data();
        aktif(false);
        setTombol(true);
        }catch(SQLException e) {
        JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        aktif(true);
        setTombol(false);
        kosong();
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_koreksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_koreksiActionPerformed
        // TODO add your handling code here:
        edit=true;
        aktif(true);
        setTombol(false);
        txt_kd_barang.setEditable(false);
    }//GEN-LAST:event_btn_koreksiActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        try{
        String sql="delete from barang where kd_barang='" + txt_kd_barang.getText()+ "'";
        stm.executeUpdate(sql);
        baca_data();
        }
        catch(SQLException e)
        {
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        aktif(false);
        setTombol(true);
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void txt_stok_minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stok_minActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stok_minActionPerformed

    private void txt_stokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stokActionPerformed

    private void txt_harga_jualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_harga_jualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_harga_jualActionPerformed

    private void combo_satuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_satuanActionPerformed
        // TODO add your handling code here:
        JComboBox cSatuan = (javax.swing.JComboBox)evt.getSource();
        //Membaca Item Yang Terpilih — > String
        sSatuan = (String)cSatuan.getSelectedItem();
    }//GEN-LAST:event_combo_satuanActionPerformed

    private void txt_nm_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nm_barangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nm_barangActionPerformed

    private void hasil_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hasil_tableMouseClicked
        // TODO add your handling code here:
        setField();
    }//GEN-LAST:event_hasil_tableMouseClicked

    private void txt_harga_beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_harga_beliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_harga_beliActionPerformed

    private void combo_satuanHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_combo_satuanHierarchyChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_combo_satuanHierarchyChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_koreksi;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JComboBox<String> combo_satuan;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel harga_beli;
    private javax.swing.JLabel harga_jual;
    private javax.swing.JTable hasil_table;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel kd_barang;
    private javax.swing.JLabel nm_barang;
    private javax.swing.JLabel satuan;
    private javax.swing.JLabel stok;
    private javax.swing.JLabel stok_min;
    private javax.swing.JTextField txt_harga_beli;
    private javax.swing.JTextField txt_harga_jual;
    private javax.swing.JTextField txt_kd_barang;
    private javax.swing.JTextField txt_nm_barang;
    private javax.swing.JTextField txt_stok;
    private javax.swing.JTextField txt_stok_min;
    // End of variables declaration//GEN-END:variables
}
